language: python
python:
  - "3.8"
addons:
  postgresql: "10"
  firefox: "72.0"
  apt:
    packages:
      - postgresql-10
      - postgresql-10-postgis-2.5
      - libhdf5-serial-dev
      - libgdal20
services:
  - xvfb
  - postgresql
before_install: 
  - wget -q -N https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux32.tar.gz
  - mkdir bin
  - tar -xzf geckodriver-v0.26.0-linux32.tar.gz --directory bin
  - export PATH=$PATH:$PWD/bin
env:
  - DJANGO=2.2
install:
  - gdal-config --version
  - pip install --upgrade pip
  - pip install -r requirements/travis-ci.txt
before_script:
  - psql -c 'ALTER ROLE travis SUPERUSER;' -U postgres
  - export DATABASE_URL="postgis://travis:@127.0.0.1:5432/stoqs"
  - echo $PATH
  - which geckodriver
  - gdal-config --version
script:  
  - ./test.sh CHANGEME load noextraload
after_script:
  - coveralls --base_dir stoqs
notifications:
  email:
    on_success: change
    on_failure: always
